apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue
spec:
  template:
    spec:
      containers:
      - name: job-queue
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "dev_user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "dev_password"