---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-queue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-queue
  template:
    metadata:
      labels:
        app: job-queue
    spec:
      containers:
      - name: job-queue
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "placeholder_user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "placeholder_pass"
        volumeMounts:
        - name: config
          mountPath: /etc/rabbitmq/rabbitmq.conf
          subPath: rabbitmq.conf
        - name: definitions
          mountPath: /etc/rabbitmq/definitions.json
          subPath: definitions.json
      volumes:
      - name: config
        configMap:
          name: rabbitmq-config
      - name: definitions
        configMap:
          name: rabbitmq-definitions
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    definitions.import_backend = local_filesystem
    definitions.local.path = /etc/rabbitmq/definitions.json
---
apiVersion: v1
kind: Service
metadata:
  name: job-queue
spec:
  selector:
    app: job-queue
  type: NodePort
  ports:
  - port: 5672
    targetPort: 5672
    nodePort: 30672
    name: amqp
